version: "3.8"

services:
  db:
    image: postgres:15
    container_name: dentalflow-db
    restart: always
    environment:
      POSTGRES_USER:  dentalflow
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB:    dentalflow_dev
    ports:
      - "5440:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
